#!/usr/bin/env python3

import sys, os, math, csv
from sys import stdin
from math import factorial, sqrt, exp, pi

filename = "./demography_data.csv"

def country_loader(data, index):
    countries =[]
    i = 0
    while i < len(data):
        countries.append(data[i][index])
        i+=1
    return countries

def countries_loader(data, index):
    countries =[]
    i = 0
    j = 0
    while i < len(data):
        try:
            index[j]
        except:
            break
        if i == index[j]:
            countries.append(data[i])
            j+=1
        i+=1
    return countries

def csv_loader():
    data = []
    with open(filename, 'r') as csv_file:
        reader = csv.reader(csv_file, delimiter=';')
        next(reader)
        for row in reader:
            data.append(row)
        return data

def compare_country(countries_l, arg, countries_w):
    i = 0
    j = 0
    index = []
    print("Country: ", sep ="", end="")
    while i < len(countries_l):
        try:
            arg[j]
        except:
            break
        if arg[j] == countries_l[i] and j == len(arg) -1:
            print(countries_w[i])
            index.append(i)
            j += 1
            i = 0
        elif arg[j] == countries_l[i]:
            print(countries_w[i], " ", sep=',' , end ="")
            index.append(i)
            j += 1
            i = 0
        i += 1
    index.sort()
    return(index)

    if j != len(arg):
        print("COUNTRY NOT FOUND", arg[j])
        exit(84)

def Fit1():
    print("Fit 1")

def Fit2():
    print("Fit 2")

def main():
    arg = []
    i = 1
    while (i < len(sys.argv)):
        arg.append(sys.argv[i])
        i += 1
    data = csv_loader()
    if len(arg) < 1:
        exit(84)
    countries_letters = country_loader(data, 1)
    countries_words = country_loader(data, 0)
    index = compare_country(countries_letters, arg, countries_words)
    countries = countries_loader(data, index)
    Fit1()
    Fit2()


main()
